### ISSUE TITLE
Contributor Assignment Agreement links broken

### ISSUE THREAD

**Issue by dtws** [Scifabric/pybossa#1453]
With reference to Contributions Assignment Agreement details posted at https://github.com/Scifabric/pybossa/blob/master/CONTRIBUTING.md, it is found that links to the associated forms, https://dl.dropboxusercontent.com/u/27667029/PyBossaIndividualContributorAssignmentAgreement.pdf and https://dl.dropboxusercontent.com/u/27667029/PyBossaEntityContributorAssignmentAgreement.pdf are broken. Request you to kindly fix the links and/or attached necessary forms here. Thanks in advance.

**Comment by dtws** [comment]
@teleyinex , @therealmarv

**Comment by kpfleming** [comment]
To clarify:

The CONTRIBUTING.md file has a link to a form on Google Docs. That form indicates that another link should be followed to obtain the form which should be signed and submitted via email. That form has links to Dropbox, but those links are stale and no documents are available at those links. The lower section of CONTRIBUTING.md repeats this information, with the same broken links to Dropbox.

It appears that the Google Docs form is supposed to be completed and submitted directly (not printed, signed, and sent via email as the form itself claims), but that is not sufficient for a corporate entity to submit a CAA. It would really be best to make this much simpler, and just allow the entity who wishes to contribute to obtain a PDF of the CAA, which they can complete, sign, and send, as the process used to be.

Also, the third line of the CONTRIBUTING.md file says "If you have any doubts about the CAA, please, contact us at .". There is no email address visible, because in the raw file it's wrapped in angle-brackets, which is not valid in a Markdown file.

**Comment by teleyinex** [comment]
Hi @kpfleming,

You are 100% right. Let me try to fix this asap so you can get the PDF, ok?

**Comment by teleyinex** [comment]
Fixed! Now go to the [Contrib](https://github.com/Scifabric/pybossa/blob/master/CONTRIBUTING.md) page and you can download the PDFs. The emails were there, but not as clickable links ;-)

**Comment by kpfleming** [comment]
Thanks, although the form still doesn't have a place for a signature which is very unusual.

**Comment by teleyinex** [comment]
The official PDF form has at the end a space for signing. Even each page has at the footer an initialled section. Please download this [PDF](https://drive.google.com/file/d/0B-wKsWbAUup4YWRxakNXVV9BYmc/view). The online form has a button for acknowledging that you agree to all the terms. If this does not work for your institution, then use the PDF linked in this comment.

**Comment by kpfleming** [comment]
We got the PDF and it will work. Thanks.
