### ISSUE TITLE
Export task runs failure

### ISSUE THREAD

**Issue by ghaimov** [Scifabric/pybossa#1753]
Hi,
Working on latest version raised issue that worked fine with previous instance.
For some reason when clicking on the export the result is an html file , while browsing tasks works fine and i can download each task results.

I am not sure if that related, but there is 'draft' icon on each operation that is not exists in our previous version.

Thanks!

**Comment by teleyinex** [comment]
Hi,

Can you check in your server your logs? That will help us to debug it.

Thanks!

**Comment by ghaimov** [comment]
Hi Daniel, 
Thanks for the reply , you want me to share supervisord.log?

found this log line in pybossa-stderr - 
[pid: 14556|app: 0|req: 31/45] 10.40.4.139 () {46 vars in 1359 bytes} [Thu Nov 23 00:41:01 2017] GET /project/resume_tagging/tasks/export => generated 12848 bytes in 19 msecs (HTTP/1.1 200) 3 headers in 368 bytes (2 switches on core 0)

**Comment by ghaimov** [comment]
[supervisord.log](https://github.com/Scifabric/pybossa/files/1499531/supervisord.log)

**Comment by alexandermendes** [comment]
That endpoint is supposed to return the HTML page, if you want to export the data you need to add the type and format query parameters, for example:

```
/project/resume_tagging/tasks/export?type=task&format=csv
```

**Comment by ghaimov** [comment]
I didn't used the RESTful API.

**Comment by ghaimov** [comment]
Using the RESTful API that worked. 
But somehow the UI (export task run) link didnt invoked the correct endpoint.

Thanks!

**Comment by alexandermendes** [comment]
That URL has nothing to do with the RESTful API...the logs show that you made a request to `/project/resume_tagging/tasks/export`. If you want to download the actual data you need to use the link above instead. 

Everything seems to be working still in the default theme, so if you're using a custom theme then I assume the link needs to be fixed.

**Comment by alexandermendes** [comment]
Ok, glad it worked then!

**Comment by ghaimov** [comment]
Just noticed that this case shares the same problem as [1711](https://github.com/Scifabric/pybossa/issues/1711).
Again, there is mew draft icon that wasn't shown in the previous version

**Comment by teleyinex** [comment]
I've experienced this not so long ago. I'll review why this could be happening.

**Comment by teleyinex** [comment]
This PR could be one fix to your issues #1772 

Do you by any chance store within the info field a list or string without any keys?

**Comment by ghaimov** [comment]
The info field in our case is a JSON string, should that fix work for us?

**Comment by teleyinex** [comment]
I would say. The problem is that the previous code only exported files with {key: value}. If your JSON has only something like this: info: [values] or info: "string" it failed. This PR solves the issue.

**Comment by ghaimov** [comment]
Hi , 
Tried the latest version with no success :\

**Comment by teleyinex** [comment]
Gosh, then I would definitely need your logs. Can you add into your settings_local.py file the LOG flag? That will write into a file any error, then you can paste it here, so we can look at it.

Basically, ensure that you have the following:

```python
LOG_FILE = 'debug.log'
import logging
LOG_LEVEL = logging.DEBUG
```

Restart the server, and then, reproduce the error. The file debug.log should show where it's the problem, so we can help you with this.

**Comment by ghaimov** [comment]
@teleyinex The log file is attached (after the changes you mentioned), the log seems to have no DEBUG messages, is that makes sense? 

We deployed the latest changes from master, yet , can't export (already have a workaround solution) and cant see stats('Ooops Sorry, the project does not have tasks to process and show some statistics' - Even though there are submitted tasks)

Anything else that I can check / share?
[pybossa-log.txt](https://github.com/Scifabric/pybossa/files/1692852/pybossa-log.txt)

**Comment by teleyinex** [comment]
Hi,

Yep, the log is not reporting anything. That's weird. Are you using supervisord as we do? We usually have two places for logging:

1.- LOG_FILE (as I said before)
2.- Supervisord stderr file for the PYBOSSA process.

Can you check if the supervisor error file has any useful information?

**Comment by ghaimov** [comment]
![image](https://user-images.githubusercontent.com/33925027/35799440-5c1a5720-0a6e-11e8-87e4-bf6b9991f7a9.png)
As you can see there is nothing useful there as well...


![image](https://user-images.githubusercontent.com/33925027/35799421-50f59184-0a6e-11e8-9dc1-57544c8d2baa.png)
You can see here the uri link to export as csv is partial - missing the args'?type=task&format=csv'

![image](https://user-images.githubusercontent.com/33925027/35799574-d8b680ba-0a6e-11e8-891a-6e384a3a1d77.png)
And there are no stats shown

Thanks for the reply!

**Comment by teleyinex** [comment]
Thanks! I see one minor detail: rq-scheduler is failing. That's not good, as it's the job that schedules jobs for generating the ZIP files in the background. While this is "not optimal", the ZIP files should be generated when you click on those links.

The statistics is not shown because of the rq-scheduler for sure. That's failing as well, and it's not generated. Thus, can you check why is not working that process?

Also, you should be able to raise the error by doing the following:

https://YOURSERVER/project/YOURPROJECTSHORTNAME/tasks/export?type=task_run&format=csv

That should generate the ZIP file on the fly. Can you try it? Please, check the LOG files while you are opening that link in your browser.

**Comment by ghaimov** [comment]
Thanks!
I managed to fix the rq-scheduler failure...
But now I see an endless loop:
![image](https://user-images.githubusercontent.com/33925027/35925796-4ca1d472-0c2f-11e8-900a-764c42bb0679.png)


A weird thing that I noticed is that it seems like the zip file is not updated (got always the same result for task run, even after submitting new tasks).
Maybe I can manually clean this file(I guess it saved somewhere)?

**Comment by teleyinex** [comment]
Hi,

Regarding the endless loop: that's expected. It runs in the background, and adds recurring jobs to the system. No worries on that.

Regarding the zip files: they are updated by the background jobs. By default they are updated every 24 hours, but you can generate new ones by just deleting them. As I guess you are not using a cloud system to store them like Rackspace, they should be located inside the pybossa/uploads folder. Check there. Delete it, try again with the previous URL. That will generate a new file.

Can you let me know if that worked?

Cheers

**Comment by ghaimov** [comment]
Removing the folder did the trick-saw the latest runs.
But still, no stats and the export task is broken, logs look fine.

**Comment by teleyinex** [comment]
It will take 24 hours to get that. You can speed the process, by making your project owner a pro. Just update the user's pro attribute to true, and it should be done in the next 10 minutes.

**Comment by ghaimov** [comment]
@teleyinex missed your comment - it didn't help anyway...

**Comment by alexandermendes** [comment]
So I think the obvious answer here is that you haven't got any task runs (i.e. no one has submitted an answer for a task)?

This would explain the stats not being produced and the export link essentially producing a download of the current page, which I think should be fixed in the default theme code (one example below).

https://github.com/Scifabric/pybossa-default-theme/blob/1cdd9c532c817aaf28ef9cfb83b71d72d1af939f/templates/projects/export.html#L23-L28

**Comment by alexandermendes** [comment]
So you could get the project ID from: 

http://{your-pybossa-domain}/api/project?short_name=resume_tagger 

then feed it into 

http://{your-pybossa-domain}/api/taskrun?project_id={project_id}&all=1 

And see if you get an empty list.

Tasks and task runs have been talked about at different times above so maybe some mix up with the terminology (just guessing of course).

**Comment by ghaimov** [comment]
@alexandermendes 
thanks for the reply, but there are submitted tasks...
I can see it via the browse page...

And I can see results via the taskrun API...

How n_tasks is assigned?

**Comment by alexandermendes** [comment]
In a background task, so http://{your-pybossa-domain}/api/projectstats?project_id={project-id} probably shows that n_task_runs is 0?

**Comment by ghaimov** [comment]
It looks worse...
no tasks, no results...
![image](https://user-images.githubusercontent.com/33925027/36198588-a86f5c0c-117f-11e8-85ae-bf93b7ae56e9.png)

After a restart to pybossa service (and manually killing rq processes), I can see paused workers:
![image](https://user-images.githubusercontent.com/33925027/36198985-d3dfbb38-1180-11e8-8b11-cb8b3139db00.png)

The logs look good with no errors...

**Comment by teleyinex** [comment]
Hi,

I think we've another user with the same problem, and we might have a new clue about what's going on.

Can you do the following? Just go to your PostreSQL DB and run the following query:

```sql

select * from project_stats where project_id=ID
```

Use the ID of the project that has everything at zero. I guess this could be the error.

**Comment by teleyinex** [comment]
See #1804

**Comment by ghaimov** [comment]
All the fields with zero value

**Comment by teleyinex** [comment]
@ghaimov ok, finally a clue :D This is the issue within your theme. Basically, it returns n_tasks = 0, so the link in the theme is href=#. Or in other words, nothing.

You can see the check [here](https://github.com/Scifabric/pybossa-default-theme/blob/master/templates/projects/export.html#L16)

So now the question is: why is that empty? You did an upgrade, from an old PYBOSSA version, correct?

**Comment by teleyinex** [comment]
I'm online right now in [gitter](gitter.im/Scifabric/pybossa) so maybe we can debug this together :-)

**Comment by ghaimov** [comment]
I would like to that but the gitter link you shared is broken :)

**Comment by teleyinex** [comment]
https://gitter.im/Scifabric/pybossa

**Comment by teleyinex** [comment]
Problem solved! It was an issue with the configuration of rq-scheduler. The template that we provide has a flag saying --db 1, and the workers were listening on redis --db 0, so this mismatch was causing the issue of not running the background jobs. This issue will fix this issue #1805

**Comment by teleyinex** [comment]
Big thanks to @ghaimov for being so patient with this :-)

**Comment by luckytoilet** [comment]
I'm experiencing the same issue.

Server logs:
```
18:28:09 scheduler.1 | 18:28:09 Checking for scheduled jobs...
18:28:09 worker.1    | 18:28:09 scheduled_jobs: pybossa.jobs.enqueue_periodic_jobs('maintenance') (756714a5-9581-48ca-907e-00f98609bc0b)
18:28:09 worker.1    | 18:28:09 Job OK, result = 1 jobs in maintenance have been enqueued
18:28:09 worker.1    | 18:28:09 Result will never expire, clean up result key manually.
18:28:09 worker.1    | 18:28:09 
18:28:09 worker.1    | 18:28:09 *** Listening on scheduled_jobs, super, high, medium, low, email, maintenance...
18:28:09 worker.1    | 18:28:09 scheduled_jobs: pybossa.jobs.enqueue_periodic_jobs('email') (92144e8e-5c8f-48ea-841d-2b4beeff3c17)
18:28:09 worker.1    | 18:28:09 Job OK, result = 0 jobs in email have been enqueued
18:28:09 worker.1    | 18:28:09 Result will never expire, clean up result key manually.
18:28:09 worker.1    | 18:28:09 
18:28:09 worker.1    | 18:28:09 *** Listening on scheduled_jobs, super, high, medium, low, email, maintenance...
18:28:09 worker.1    | 18:28:09 maintenance: pybossa.jobs.check_failed() (dfc8281f-e267-44fb-abbf-4e6a45c660fe)
18:28:09 worker.1    | 18:28:09 Job OK, result = JOBS: ['b2194c72-96e8-4381-9043-1a7d56b744d7', '37f2a2ce-ce28-47ed-b4a3-042115e44537'] You have failed the system.
18:28:09 worker.1    | 18:28:09 Result is kept for 500 seconds.
18:28:09 worker.1    | 18:28:09 
18:28:09 worker.1    | 18:28:09 *** Listening on scheduled_jobs, super, high, medium, low, email, maintenance...
18:29:09 scheduler.1 | 18:29:09 Checking for scheduled jobs...
18:29:09 worker.1    | 18:29:09 scheduled_jobs: pybossa.jobs.enqueue_periodic_jobs('maintenance') (756714a5-9581-48ca-907e-00f98609bc0b)
18:29:09 worker.1    | 18:29:09 Job OK, result = 1 jobs in maintenance have been enqueued
18:29:09 worker.1    | 18:29:09 Result will never expire, clean up result key manually.
18:29:09 worker.1    | 18:29:09 
18:29:09 worker.1    | 18:29:09 *** Listening on scheduled_jobs, super, high, medium, low, email, maintenance...
18:29:09 worker.1    | 18:29:09 scheduled_jobs: pybossa.jobs.enqueue_periodic_jobs('email') (92144e8e-5c8f-48ea-841d-2b4beeff3c17)
18:29:09 worker.1    | 18:29:09 Job OK, result = 0 jobs in email have been enqueued
18:29:09 worker.1    | 18:29:09 Result will never expire, clean up result key manually.
18:29:09 worker.1    | 18:29:09 
18:29:09 worker.1    | 18:29:09 *** Listening on scheduled_jobs, super, high, medium, low, email, maintenance...
18:29:09 worker.1    | 18:29:09 maintenance: pybossa.jobs.check_failed() (1bab9bee-819f-4623-ada8-2b85c9a0e172)
18:29:09 worker.1    | 18:29:09 Job OK, result = JOBS: ['b2194c72-96e8-4381-9043-1a7d56b744d7', '37f2a2ce-ce28-47ed-b4a3-042115e44537'] You have failed the system.
18:29:09 worker.1    | 18:29:09 Result is kept for 500 seconds.
18:29:09 worker.1    | 18:29:09 
18:29:09 worker.1    | 18:29:09 *** Listening on scheduled_jobs, super, high, medium, low, email, maintenance...
```

So the scheduler is running.

I made a Procfile according to your suggestion above:

```
worker: python app_context_rqworker.py scheduled_jobs super high medium low email maintenance
scheduler: rqscheduler --host 127.0.0.1 --port 6379 --interval 60 --db 0
pybossa: python run.py
```

However, I'm still getting an html file when I try to export. Strangely, the project state shows "draft" even when the project has been published:

![screenshot from 2018-06-26 14-38-36](https://user-images.githubusercontent.com/123435/41932485-1734b04c-794f-11e8-9eeb-4aea29310654.png)

Any help would be appreciated, thanks!

**Comment by teleyinex** [comment]
Flush Redis, restart pybossa and the workers and try again. Let us know if it fixes the problem or if it stills there.

**Comment by teleyinex** [comment]
Gosh. Let me try with a clean installation, so we can debug it properly.

**Comment by NanyiJiang** [comment]
https://github.com/NanyiJiang/pybossa-docker-compose-issue

hi @teleyinex , this is our setup in docker-compose format. I work with @luckytoilet on this issue. hope this can help you reproduce(or point out the errors we might have made). thanks!

**Comment by NanyiJiang** [comment]
any update for this?

**Comment by teleyinex** [comment]
I've been able to replicate it, so I'm going to fix it.

**Comment by teleyinex** [comment]
Fixed [here](https://github.com/Scifabric/pybossa-default-theme/pull/173)

**Comment by teleyinex** [comment]
Now merged into default. Waiting for the tests, in principle it should pass without problems. This was fixed a long time ago, so I guess we re-introduced it from another branch in the default theme.

**Comment by teleyinex** [comment]
@NanyiJiang can you try with the new pybossa-default-theme?

**Comment by NanyiJiang** [comment]
@teleyinex thanks for following up. the issue persists with the lastest master branch, however i start to get this in my worker log:

```pybossa_1  | 15:54:18 worker.1    | 15:54:18 Job OK, result = JOBS: ['8b116437-6ec2-484a-8aca-f3aef242b37f'] You have failed the system.
pybossa_1  | 15:54:18 worker.1    | 15:54:18 Result is kept for 500 seconds.
pybossa_1  | 15:54:18 worker.1    | 15:54:18 
pybossa_1  | 15:54:18 worker.1    | 15:54:18 *** Listening on scheduled_jobs, super, high, medium, low, email, maintenance...
pybossa_1  | 15:54:18 worker.1    | 15:54:18 low: pybossa.jobs.warn_old_project_owners() (8b116437-6ec2-484a-8aca-f3aef242b37f)
pybossa_1  | 15:54:18 worker.1    | /usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
pybossa_1  | 15:54:18 worker.1    |   """)
pybossa_1  | 15:54:18 worker.1    | 15:54:18 error: [Errno 99] Cannot assign requested address
pybossa_1  | 15:54:18 worker.1    | Traceback (most recent call last):
pybossa_1  | 15:54:18 worker.1    |   File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 479, in perform_job
pybossa_1  | 15:54:18 worker.1    |     rv = job.perform()
pybossa_1  | 15:54:18 worker.1    |   File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 466, in perform
db_1       | LOG:  unexpected EOF on client connection with an open transaction


```

I dont believe i've seen this before. could be a separate issue.

I've updated my dockersetup here:
https://github.com/NanyiJiang/pybossa-docker-compose-issue

**Comment by teleyinex** [comment]
The fix basically does the following: it forces PYBOSSA to create a ZIP file if it doesn't exist. This is done via the pybossa/themes/default. Can you check that you got the latest version of the default theme? You need to be in this [commit](https://github.com/Scifabric/pybossa-default-theme/commit/94a6e8257e998df9ff388e95adb87eccaa423e45)
